# Generated by Django 3.0.4 on 2020-03-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20200317_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
