# Generated by Django 3.0.4 on 2020-03-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
