# Generated by Django 3.0.4 on 2020-04-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_auto_20200318_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
